services:
  web:
    image: php:8.0-apache
    container_name: php-apache3
    platform: linux/amd64
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: mysql-db3
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin3
    platform: linux/amd64
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MySQL_ROOT_PASSWORD: root
    ports:
    - "8081:80"